<a href="https://colab.research.google.com/github/VNP-SSD/FDS_PRACTICALS/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 NUMPY ***LIBRARY***

In [1]:
print('hello')

hello


In [2]:
a = 2
a

2

In [3]:
a = 2
b = 3
print('a = '+str(a)+' and '+'b = '+str(b))

a = 2 and b = 3


In [4]:
type(a)


int

In [5]:
s1 = 'DALE STYEN'
type(s1)

str

In [6]:
f=2.34546796547
type(f)

float

indent


https://numpy.org/doc/stable/user/whatisnumpy.html

In [8]:
a=[1,2,3]
a

[1, 2, 3]

In [9]:
type(a)


list

In [10]:
b=[4,5,6]
b

[4, 5, 6]

In [11]:
c = []
for i in range(len(a)):
  c.append(a[i]*b[i])
c

[4, 10, 18]

In [12]:
c = []
for i in range(len(a)):
  c.append(a[i]+b[i])
c

[5, 7, 9]

In [15]:
import time
print('sleeping')
time.sleep(30)
print('done sleeping')

sleeping
done sleeping


In [14]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
a.ndim

2

In [17]:
a.dtype

dtype('int64')

In [18]:
a.dtype.name

'int64'

In [19]:
a.itemsize


8

In [ ]:
a.size


In [20]:
type(a)


numpy.ndarray

In [21]:
b=np.array([[11,13,14],[56,57,58]])
b

array([[11, 13, 14],
       [56, 57, 58]])

In [22]:
b.reshape(3,2)
b

array([[11, 13, 14],
       [56, 57, 58]])

In [23]:
c=b.reshape(3,2)
c

array([[11, 13],
       [14, 56],
       [57, 58]])

In [24]:
d=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')

In [25]:
e=d.reshape(2,5)
e

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')